---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:

    - name: Install packages
      packages:
        name:
          - htop
          - mc
          - byobu