---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  tasks:
  - name: Install packages
    package:
      name:
        - htop
        - tmux
        - neovim
        - vim-nox
        - exa

  - name: copy wallpaper file
    copy:
      src: files/IMG_1933.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    dconf: 
      key: "/org/gnome/desktop/background/picrture-uri"
      value:  "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpeper position
    dconf
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
