---
- hosts: localhost 
  connection: local
  become: true
  vars:
    - the_user: peterg

  pre_tasks:
  - name: update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: install prereq for dconf
    apt:
      name:
        - python3-psutil

  tasks:
  - name: Install packages
    apt:
      name:
        # - htop
        # - tmux
        # - neovim
        # - vim-nox
        - exa

  tasks:
  - name: copy wallpaper file
    copy:
      src: files/IMG_1933.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: "{{ the_user }}"
    dconf: 
      key: "/org/gnome/desktop/background/picrture-uri"
      value:  "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: "{{ the_user }}"
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
