---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - include: tasks/utility-packages.yml
    - include: tasks/users.yml
